name: Auto Merge on Success

on:
  pull_request:
    types: [opened, synchronize, reopened]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    if: github.event.pull_request.user.login == 'BritainSmith'
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge on success
        uses: actions/github-script@v7
        with:
          script: |
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });
            
            const allChecksPassed = checks.check_runs.every(check => 
              check.conclusion === 'success' || check.conclusion === 'skipped'
            );
            
            if (allChecksPassed) {
              try {
                await github.rest.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.payload.pull_request.number,
                  merge_method: 'squash',
                });
                console.log('✅ Auto-merged PR successfully');
              } catch (error) {
                console.log('❌ Auto-merge failed:', error.message);
              }
            } else {
              console.log('⏳ Waiting for all checks to pass...');
            } 